# custom_components/ev_charger_modbus/services.yaml
set_charging_current:
  name: Set charging current
  description: Set the charging current of the EV charger.
  target:
    entity:
      integration: ev_charger_modbus
      domain: number
  fields:
    current:
      name: Current
      description: The charging current in amperes (between 5 and configured maximum)
      required: true
      selector:
        number:
          min: 5
          max: 32  # This will be limited by the entity's configuration
          step: 1
          mode: slider