# Service to set charging current
set_charging_current:
  name: Set charging current
  description: Sets the charging current for an EV charger
  target:
    entity:
      domain: number
      integration: ev_charger_modbus
  fields:
    current:
      name: Current
      description: Set to 0A to stop charging, or between 5A and the maximum charger amperage
      required: true
      selector:
        number:
          min: 0
          max: 32
          step: 1
          mode: slider
          unit_of_measurement: A
